name: Pattern Lint

on:
  push:
    paths: ['**/*.rb', '**/*.gemspec', '**/Gemfile', '**/Gemfile.lock']
  pull_request:
    branches: [main]
    paths: ['**/*.rb', '**/*.gemspec', '**/Gemfile', '**/Gemfile.lock']

jobs:
  lint:
    uses: LegionIO/.github/.github/workflows/lint-patterns.yml@main
